- name: Install bottle for Python 3.9 specifically, using the 'pip3.9 executable
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - PyMySQL
  - cryptography

- name: Install MySQL Server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start and enable mysql
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Check the connection of mysql
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: mysql.deaws82s.online
  register: mysql_info
  ignore_errors: true

- name: print output
  ansible.builtin.debug:
    msg: "Mysql info: {{ mysql_info }}"

- name: setup root password
  ansible.builtin.command: " mysql_secure_installation --set-root-pass {{ mysql_root_password }} "
  when: mysql_info.failed is true